version: 0.3.{build}
skip_tags: true
image: Visual Studio 2026
configuration: Release
platform: x64
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  VCPKG_MAX_CONCURRENCY: 4
cache:
- '%USERPROFILE%\.nuget\packages'
build_script:
- cmd: msbuild macro_record.sln /restore /m /p:Configuration=Release /p:Platform=x64 /p:RestorePackagesConfig=true /verbosity:minimal
test_script:
- cmd: dotnet test MacroRecorderGUITests\MacroRecorderGUITests.csproj -c Release -p:Platform=x64 --no-build --verbosity minimal
after_build:
- cmd: '%APPVEYOR_BUILD_FOLDER%\appveyor-after-build-script.cmd'
artifacts:
- path: x64\Release\macro_record-$(APPVEYOR_BUILD_VERSION)-x64-Release.zip
  name: macro_record-$(APPVEYOR_BUILD_VERSION)-x64-Release.zip
- path: x64\Release\MacroRecorderSetup-x64-$(APPVEYOR_BUILD_VERSION).exe
  name: MacroRecorderSetup-x64-$(APPVEYOR_BUILD_VERSION).exe
deploy:
- provider: GitHub
  auth_token:
    secure: nqWTKB0lazjRUBIeMe4+znfMXwaGJYhUT7qS2WxsRuuCKZrxrFimphsoxHAXAxOk
  prerelease: true
  on:
    branch: master
