// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Events.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtobufGenerated {

  /// <summary>Holder for reflection information generated from Events.proto</summary>
  public static partial class EventsReflection {

    #region Descriptor
    /// <summary>File descriptor for Events.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EventsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxFdmVudHMucHJvdG8SEXByb3RvYnVmR2VuZXJhdGVkIqEDChJQcm90b2J1",
            "ZklucHV0RXZlbnQSGgoSdGltZVNpbmNlTGFzdEV2ZW50GAEgASgEElAKDWtl",
            "eWJvYXJkRXZlbnQYAiABKAsyNy5wcm90b2J1ZkdlbmVyYXRlZC5Qcm90b2J1",
            "ZklucHV0RXZlbnQuS2V5Ym9hcmRFdmVudFR5cGVIABJKCgptb3VzZUV2ZW50",
            "GAMgASgLMjQucHJvdG9idWZHZW5lcmF0ZWQuUHJvdG9idWZJbnB1dEV2ZW50",
            "Lk1vdXNlRXZlbnRUeXBlSAAaOgoRS2V5Ym9hcmRFdmVudFR5cGUSFgoOdmly",
            "dHVhbEtleUNvZGUYASABKA0SDQoFa2V5VXAYAiABKAgaiwEKDk1vdXNlRXZl",
            "bnRUeXBlEgkKAXgYASABKAUSCQoBeRgCIAEoBRISCgphY3Rpb25UeXBlGAMg",
            "ASgNEhUKDXdoZWVsUm90YXRpb24YBCABKA0SGAoQcmVsYXRpdmVQb3NpdGlv",
            "bhgFIAEoCBIeChZtYXBwZWRUb1ZpcnR1YWxEZXNrdG9wGAYgASgIQgcKBUV2",
            "ZW50IlQKFlByb3RvYnVmSW5wdXRFdmVudExpc3QSOgoLaW5wdXRFdmVudHMY",
            "ASADKAsyJS5wcm90b2J1ZkdlbmVyYXRlZC5Qcm90b2J1ZklucHV0RXZlbnRi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufGenerated.ProtobufInputEvent), global::ProtobufGenerated.ProtobufInputEvent.Parser, new[]{ "TimeSinceLastEvent", "KeyboardEvent", "MouseEvent" }, new[]{ "Event" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufGenerated.ProtobufInputEvent.Types.KeyboardEventType), global::ProtobufGenerated.ProtobufInputEvent.Types.KeyboardEventType.Parser, new[]{ "VirtualKeyCode", "KeyUp" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufGenerated.ProtobufInputEvent.Types.MouseEventType), global::ProtobufGenerated.ProtobufInputEvent.Types.MouseEventType.Parser, new[]{ "X", "Y", "ActionType", "WheelRotation", "RelativePosition", "MappedToVirtualDesktop" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufGenerated.ProtobufInputEventList), global::ProtobufGenerated.ProtobufInputEventList.Parser, new[]{ "InputEvents" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ProtobufInputEvent : pb::IMessage<ProtobufInputEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufInputEvent> _parser = new pb::MessageParser<ProtobufInputEvent>(() => new ProtobufInputEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufInputEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtobufGenerated.EventsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufInputEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufInputEvent(ProtobufInputEvent other) : this() {
      timeSinceLastEvent_ = other.timeSinceLastEvent_;
      switch (other.EventCase) {
        case EventOneofCase.KeyboardEvent:
          KeyboardEvent = other.KeyboardEvent.Clone();
          break;
        case EventOneofCase.MouseEvent:
          MouseEvent = other.MouseEvent.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufInputEvent Clone() {
      return new ProtobufInputEvent(this);
    }

    /// <summary>Field number for the "timeSinceLastEvent" field.</summary>
    public const int TimeSinceLastEventFieldNumber = 1;
    private ulong timeSinceLastEvent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TimeSinceLastEvent {
      get { return timeSinceLastEvent_; }
      set {
        timeSinceLastEvent_ = value;
      }
    }

    /// <summary>Field number for the "keyboardEvent" field.</summary>
    public const int KeyboardEventFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProtobufGenerated.ProtobufInputEvent.Types.KeyboardEventType KeyboardEvent {
      get { return eventCase_ == EventOneofCase.KeyboardEvent ? (global::ProtobufGenerated.ProtobufInputEvent.Types.KeyboardEventType) event_ : null; }
      set {
        event_ = value;
        eventCase_ = value == null ? EventOneofCase.None : EventOneofCase.KeyboardEvent;
      }
    }

    /// <summary>Field number for the "mouseEvent" field.</summary>
    public const int MouseEventFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProtobufGenerated.ProtobufInputEvent.Types.MouseEventType MouseEvent {
      get { return eventCase_ == EventOneofCase.MouseEvent ? (global::ProtobufGenerated.ProtobufInputEvent.Types.MouseEventType) event_ : null; }
      set {
        event_ = value;
        eventCase_ = value == null ? EventOneofCase.None : EventOneofCase.MouseEvent;
      }
    }

    private object event_;
    /// <summary>Enum of possible cases for the "Event" oneof.</summary>
    public enum EventOneofCase {
      None = 0,
      KeyboardEvent = 2,
      MouseEvent = 3,
    }
    private EventOneofCase eventCase_ = EventOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventOneofCase EventCase {
      get { return eventCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEvent() {
      eventCase_ = EventOneofCase.None;
      event_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufInputEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufInputEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TimeSinceLastEvent != other.TimeSinceLastEvent) return false;
      if (!object.Equals(KeyboardEvent, other.KeyboardEvent)) return false;
      if (!object.Equals(MouseEvent, other.MouseEvent)) return false;
      if (EventCase != other.EventCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TimeSinceLastEvent != 0UL) hash ^= TimeSinceLastEvent.GetHashCode();
      if (eventCase_ == EventOneofCase.KeyboardEvent) hash ^= KeyboardEvent.GetHashCode();
      if (eventCase_ == EventOneofCase.MouseEvent) hash ^= MouseEvent.GetHashCode();
      hash ^= (int) eventCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TimeSinceLastEvent != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(TimeSinceLastEvent);
      }
      if (eventCase_ == EventOneofCase.KeyboardEvent) {
        output.WriteRawTag(18);
        output.WriteMessage(KeyboardEvent);
      }
      if (eventCase_ == EventOneofCase.MouseEvent) {
        output.WriteRawTag(26);
        output.WriteMessage(MouseEvent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TimeSinceLastEvent != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(TimeSinceLastEvent);
      }
      if (eventCase_ == EventOneofCase.KeyboardEvent) {
        output.WriteRawTag(18);
        output.WriteMessage(KeyboardEvent);
      }
      if (eventCase_ == EventOneofCase.MouseEvent) {
        output.WriteRawTag(26);
        output.WriteMessage(MouseEvent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TimeSinceLastEvent != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TimeSinceLastEvent);
      }
      if (eventCase_ == EventOneofCase.KeyboardEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(KeyboardEvent);
      }
      if (eventCase_ == EventOneofCase.MouseEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MouseEvent);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufInputEvent other) {
      if (other == null) {
        return;
      }
      if (other.TimeSinceLastEvent != 0UL) {
        TimeSinceLastEvent = other.TimeSinceLastEvent;
      }
      switch (other.EventCase) {
        case EventOneofCase.KeyboardEvent:
          if (KeyboardEvent == null) {
            KeyboardEvent = new global::ProtobufGenerated.ProtobufInputEvent.Types.KeyboardEventType();
          }
          KeyboardEvent.MergeFrom(other.KeyboardEvent);
          break;
        case EventOneofCase.MouseEvent:
          if (MouseEvent == null) {
            MouseEvent = new global::ProtobufGenerated.ProtobufInputEvent.Types.MouseEventType();
          }
          MouseEvent.MergeFrom(other.MouseEvent);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TimeSinceLastEvent = input.ReadUInt64();
            break;
          }
          case 18: {
            global::ProtobufGenerated.ProtobufInputEvent.Types.KeyboardEventType subBuilder = new global::ProtobufGenerated.ProtobufInputEvent.Types.KeyboardEventType();
            if (eventCase_ == EventOneofCase.KeyboardEvent) {
              subBuilder.MergeFrom(KeyboardEvent);
            }
            input.ReadMessage(subBuilder);
            KeyboardEvent = subBuilder;
            break;
          }
          case 26: {
            global::ProtobufGenerated.ProtobufInputEvent.Types.MouseEventType subBuilder = new global::ProtobufGenerated.ProtobufInputEvent.Types.MouseEventType();
            if (eventCase_ == EventOneofCase.MouseEvent) {
              subBuilder.MergeFrom(MouseEvent);
            }
            input.ReadMessage(subBuilder);
            MouseEvent = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TimeSinceLastEvent = input.ReadUInt64();
            break;
          }
          case 18: {
            global::ProtobufGenerated.ProtobufInputEvent.Types.KeyboardEventType subBuilder = new global::ProtobufGenerated.ProtobufInputEvent.Types.KeyboardEventType();
            if (eventCase_ == EventOneofCase.KeyboardEvent) {
              subBuilder.MergeFrom(KeyboardEvent);
            }
            input.ReadMessage(subBuilder);
            KeyboardEvent = subBuilder;
            break;
          }
          case 26: {
            global::ProtobufGenerated.ProtobufInputEvent.Types.MouseEventType subBuilder = new global::ProtobufGenerated.ProtobufInputEvent.Types.MouseEventType();
            if (eventCase_ == EventOneofCase.MouseEvent) {
              subBuilder.MergeFrom(MouseEvent);
            }
            input.ReadMessage(subBuilder);
            MouseEvent = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ProtobufInputEvent message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class KeyboardEventType : pb::IMessage<KeyboardEventType>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<KeyboardEventType> _parser = new pb::MessageParser<KeyboardEventType>(() => new KeyboardEventType());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<KeyboardEventType> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::ProtobufGenerated.ProtobufInputEvent.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public KeyboardEventType() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public KeyboardEventType(KeyboardEventType other) : this() {
          virtualKeyCode_ = other.virtualKeyCode_;
          keyUp_ = other.keyUp_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public KeyboardEventType Clone() {
          return new KeyboardEventType(this);
        }

        /// <summary>Field number for the "virtualKeyCode" field.</summary>
        public const int VirtualKeyCodeFieldNumber = 1;
        private uint virtualKeyCode_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint VirtualKeyCode {
          get { return virtualKeyCode_; }
          set {
            virtualKeyCode_ = value;
          }
        }

        /// <summary>Field number for the "keyUp" field.</summary>
        public const int KeyUpFieldNumber = 2;
        private bool keyUp_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool KeyUp {
          get { return keyUp_; }
          set {
            keyUp_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as KeyboardEventType);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(KeyboardEventType other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (VirtualKeyCode != other.VirtualKeyCode) return false;
          if (KeyUp != other.KeyUp) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (VirtualKeyCode != 0) hash ^= VirtualKeyCode.GetHashCode();
          if (KeyUp != false) hash ^= KeyUp.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (VirtualKeyCode != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(VirtualKeyCode);
          }
          if (KeyUp != false) {
            output.WriteRawTag(16);
            output.WriteBool(KeyUp);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (VirtualKeyCode != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(VirtualKeyCode);
          }
          if (KeyUp != false) {
            output.WriteRawTag(16);
            output.WriteBool(KeyUp);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (VirtualKeyCode != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(VirtualKeyCode);
          }
          if (KeyUp != false) {
            size += 1 + 1;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(KeyboardEventType other) {
          if (other == null) {
            return;
          }
          if (other.VirtualKeyCode != 0) {
            VirtualKeyCode = other.VirtualKeyCode;
          }
          if (other.KeyUp != false) {
            KeyUp = other.KeyUp;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                VirtualKeyCode = input.ReadUInt32();
                break;
              }
              case 16: {
                KeyUp = input.ReadBool();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                VirtualKeyCode = input.ReadUInt32();
                break;
              }
              case 16: {
                KeyUp = input.ReadBool();
                break;
              }
            }
          }
        }
        #endif

      }

      public sealed partial class MouseEventType : pb::IMessage<MouseEventType>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<MouseEventType> _parser = new pb::MessageParser<MouseEventType>(() => new MouseEventType());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<MouseEventType> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::ProtobufGenerated.ProtobufInputEvent.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public MouseEventType() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public MouseEventType(MouseEventType other) : this() {
          x_ = other.x_;
          y_ = other.y_;
          actionType_ = other.actionType_;
          wheelRotation_ = other.wheelRotation_;
          relativePosition_ = other.relativePosition_;
          mappedToVirtualDesktop_ = other.mappedToVirtualDesktop_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public MouseEventType Clone() {
          return new MouseEventType(this);
        }

        /// <summary>Field number for the "x" field.</summary>
        public const int XFieldNumber = 1;
        private int x_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int X {
          get { return x_; }
          set {
            x_ = value;
          }
        }

        /// <summary>Field number for the "y" field.</summary>
        public const int YFieldNumber = 2;
        private int y_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Y {
          get { return y_; }
          set {
            y_ = value;
          }
        }

        /// <summary>Field number for the "actionType" field.</summary>
        public const int ActionTypeFieldNumber = 3;
        private uint actionType_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint ActionType {
          get { return actionType_; }
          set {
            actionType_ = value;
          }
        }

        /// <summary>Field number for the "wheelRotation" field.</summary>
        public const int WheelRotationFieldNumber = 4;
        private uint wheelRotation_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint WheelRotation {
          get { return wheelRotation_; }
          set {
            wheelRotation_ = value;
          }
        }

        /// <summary>Field number for the "relativePosition" field.</summary>
        public const int RelativePositionFieldNumber = 5;
        private bool relativePosition_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool RelativePosition {
          get { return relativePosition_; }
          set {
            relativePosition_ = value;
          }
        }

        /// <summary>Field number for the "mappedToVirtualDesktop" field.</summary>
        public const int MappedToVirtualDesktopFieldNumber = 6;
        private bool mappedToVirtualDesktop_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool MappedToVirtualDesktop {
          get { return mappedToVirtualDesktop_; }
          set {
            mappedToVirtualDesktop_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as MouseEventType);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(MouseEventType other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (X != other.X) return false;
          if (Y != other.Y) return false;
          if (ActionType != other.ActionType) return false;
          if (WheelRotation != other.WheelRotation) return false;
          if (RelativePosition != other.RelativePosition) return false;
          if (MappedToVirtualDesktop != other.MappedToVirtualDesktop) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (X != 0) hash ^= X.GetHashCode();
          if (Y != 0) hash ^= Y.GetHashCode();
          if (ActionType != 0) hash ^= ActionType.GetHashCode();
          if (WheelRotation != 0) hash ^= WheelRotation.GetHashCode();
          if (RelativePosition != false) hash ^= RelativePosition.GetHashCode();
          if (MappedToVirtualDesktop != false) hash ^= MappedToVirtualDesktop.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (X != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(X);
          }
          if (Y != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(Y);
          }
          if (ActionType != 0) {
            output.WriteRawTag(24);
            output.WriteUInt32(ActionType);
          }
          if (WheelRotation != 0) {
            output.WriteRawTag(32);
            output.WriteUInt32(WheelRotation);
          }
          if (RelativePosition != false) {
            output.WriteRawTag(40);
            output.WriteBool(RelativePosition);
          }
          if (MappedToVirtualDesktop != false) {
            output.WriteRawTag(48);
            output.WriteBool(MappedToVirtualDesktop);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (X != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(X);
          }
          if (Y != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(Y);
          }
          if (ActionType != 0) {
            output.WriteRawTag(24);
            output.WriteUInt32(ActionType);
          }
          if (WheelRotation != 0) {
            output.WriteRawTag(32);
            output.WriteUInt32(WheelRotation);
          }
          if (RelativePosition != false) {
            output.WriteRawTag(40);
            output.WriteBool(RelativePosition);
          }
          if (MappedToVirtualDesktop != false) {
            output.WriteRawTag(48);
            output.WriteBool(MappedToVirtualDesktop);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (X != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(X);
          }
          if (Y != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Y);
          }
          if (ActionType != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ActionType);
          }
          if (WheelRotation != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(WheelRotation);
          }
          if (RelativePosition != false) {
            size += 1 + 1;
          }
          if (MappedToVirtualDesktop != false) {
            size += 1 + 1;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(MouseEventType other) {
          if (other == null) {
            return;
          }
          if (other.X != 0) {
            X = other.X;
          }
          if (other.Y != 0) {
            Y = other.Y;
          }
          if (other.ActionType != 0) {
            ActionType = other.ActionType;
          }
          if (other.WheelRotation != 0) {
            WheelRotation = other.WheelRotation;
          }
          if (other.RelativePosition != false) {
            RelativePosition = other.RelativePosition;
          }
          if (other.MappedToVirtualDesktop != false) {
            MappedToVirtualDesktop = other.MappedToVirtualDesktop;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                X = input.ReadInt32();
                break;
              }
              case 16: {
                Y = input.ReadInt32();
                break;
              }
              case 24: {
                ActionType = input.ReadUInt32();
                break;
              }
              case 32: {
                WheelRotation = input.ReadUInt32();
                break;
              }
              case 40: {
                RelativePosition = input.ReadBool();
                break;
              }
              case 48: {
                MappedToVirtualDesktop = input.ReadBool();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                X = input.ReadInt32();
                break;
              }
              case 16: {
                Y = input.ReadInt32();
                break;
              }
              case 24: {
                ActionType = input.ReadUInt32();
                break;
              }
              case 32: {
                WheelRotation = input.ReadUInt32();
                break;
              }
              case 40: {
                RelativePosition = input.ReadBool();
                break;
              }
              case 48: {
                MappedToVirtualDesktop = input.ReadBool();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  public sealed partial class ProtobufInputEventList : pb::IMessage<ProtobufInputEventList>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufInputEventList> _parser = new pb::MessageParser<ProtobufInputEventList>(() => new ProtobufInputEventList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufInputEventList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtobufGenerated.EventsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufInputEventList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufInputEventList(ProtobufInputEventList other) : this() {
      inputEvents_ = other.inputEvents_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufInputEventList Clone() {
      return new ProtobufInputEventList(this);
    }

    /// <summary>Field number for the "inputEvents" field.</summary>
    public const int InputEventsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ProtobufGenerated.ProtobufInputEvent> _repeated_inputEvents_codec
        = pb::FieldCodec.ForMessage(10, global::ProtobufGenerated.ProtobufInputEvent.Parser);
    private readonly pbc::RepeatedField<global::ProtobufGenerated.ProtobufInputEvent> inputEvents_ = new pbc::RepeatedField<global::ProtobufGenerated.ProtobufInputEvent>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ProtobufGenerated.ProtobufInputEvent> InputEvents {
      get { return inputEvents_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufInputEventList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufInputEventList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!inputEvents_.Equals(other.inputEvents_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= inputEvents_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      inputEvents_.WriteTo(output, _repeated_inputEvents_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      inputEvents_.WriteTo(ref output, _repeated_inputEvents_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += inputEvents_.CalculateSize(_repeated_inputEvents_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufInputEventList other) {
      if (other == null) {
        return;
      }
      inputEvents_.Add(other.inputEvents_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            inputEvents_.AddEntriesFrom(input, _repeated_inputEvents_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            inputEvents_.AddEntriesFrom(ref input, _repeated_inputEvents_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
