// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Events.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Events_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Events_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Events_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Events_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Events_2eproto;
namespace protobufGenerated {
class ProtobufInputEvent;
struct ProtobufInputEventDefaultTypeInternal;
extern ProtobufInputEventDefaultTypeInternal _ProtobufInputEvent_default_instance_;
class ProtobufInputEventList;
struct ProtobufInputEventListDefaultTypeInternal;
extern ProtobufInputEventListDefaultTypeInternal _ProtobufInputEventList_default_instance_;
class ProtobufInputEvent_KeyboardEventType;
struct ProtobufInputEvent_KeyboardEventTypeDefaultTypeInternal;
extern ProtobufInputEvent_KeyboardEventTypeDefaultTypeInternal _ProtobufInputEvent_KeyboardEventType_default_instance_;
class ProtobufInputEvent_MouseEventType;
struct ProtobufInputEvent_MouseEventTypeDefaultTypeInternal;
extern ProtobufInputEvent_MouseEventTypeDefaultTypeInternal _ProtobufInputEvent_MouseEventType_default_instance_;
}  // namespace protobufGenerated
PROTOBUF_NAMESPACE_OPEN
template<> ::protobufGenerated::ProtobufInputEvent* Arena::CreateMaybeMessage<::protobufGenerated::ProtobufInputEvent>(Arena*);
template<> ::protobufGenerated::ProtobufInputEventList* Arena::CreateMaybeMessage<::protobufGenerated::ProtobufInputEventList>(Arena*);
template<> ::protobufGenerated::ProtobufInputEvent_KeyboardEventType* Arena::CreateMaybeMessage<::protobufGenerated::ProtobufInputEvent_KeyboardEventType>(Arena*);
template<> ::protobufGenerated::ProtobufInputEvent_MouseEventType* Arena::CreateMaybeMessage<::protobufGenerated::ProtobufInputEvent_MouseEventType>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protobufGenerated {

// ===================================================================

class ProtobufInputEvent_KeyboardEventType final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobufGenerated.ProtobufInputEvent.KeyboardEventType) */ {
 public:
  inline ProtobufInputEvent_KeyboardEventType() : ProtobufInputEvent_KeyboardEventType(nullptr) {}
  ~ProtobufInputEvent_KeyboardEventType() override;
  explicit PROTOBUF_CONSTEXPR ProtobufInputEvent_KeyboardEventType(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ProtobufInputEvent_KeyboardEventType(const ProtobufInputEvent_KeyboardEventType& from);
  ProtobufInputEvent_KeyboardEventType(ProtobufInputEvent_KeyboardEventType&& from) noexcept
    : ProtobufInputEvent_KeyboardEventType() {
    *this = ::std::move(from);
  }

  inline ProtobufInputEvent_KeyboardEventType& operator=(const ProtobufInputEvent_KeyboardEventType& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtobufInputEvent_KeyboardEventType& operator=(ProtobufInputEvent_KeyboardEventType&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtobufInputEvent_KeyboardEventType& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProtobufInputEvent_KeyboardEventType* internal_default_instance() {
    return reinterpret_cast<const ProtobufInputEvent_KeyboardEventType*>(
               &_ProtobufInputEvent_KeyboardEventType_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ProtobufInputEvent_KeyboardEventType& a, ProtobufInputEvent_KeyboardEventType& b) {
    a.Swap(&b);
  }
  inline void Swap(ProtobufInputEvent_KeyboardEventType* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtobufInputEvent_KeyboardEventType* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtobufInputEvent_KeyboardEventType* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ProtobufInputEvent_KeyboardEventType>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ProtobufInputEvent_KeyboardEventType& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ProtobufInputEvent_KeyboardEventType& from) {
    ProtobufInputEvent_KeyboardEventType::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProtobufInputEvent_KeyboardEventType* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobufGenerated.ProtobufInputEvent.KeyboardEventType";
  }
  protected:
  explicit ProtobufInputEvent_KeyboardEventType(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVirtualKeyCodeFieldNumber = 1,
    kKeyUpFieldNumber = 2,
  };
  // uint32 virtualKeyCode = 1;
  void clear_virtualkeycode();
  uint32_t virtualkeycode() const;
  void set_virtualkeycode(uint32_t value);
  private:
  uint32_t _internal_virtualkeycode() const;
  void _internal_set_virtualkeycode(uint32_t value);
  public:

  // bool keyUp = 2;
  void clear_keyup();
  bool keyup() const;
  void set_keyup(bool value);
  private:
  bool _internal_keyup() const;
  void _internal_set_keyup(bool value);
  public:

  // @@protoc_insertion_point(class_scope:protobufGenerated.ProtobufInputEvent.KeyboardEventType)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t virtualkeycode_;
    bool keyup_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Events_2eproto;
};
// -------------------------------------------------------------------

class ProtobufInputEvent_MouseEventType final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobufGenerated.ProtobufInputEvent.MouseEventType) */ {
 public:
  inline ProtobufInputEvent_MouseEventType() : ProtobufInputEvent_MouseEventType(nullptr) {}
  ~ProtobufInputEvent_MouseEventType() override;
  explicit PROTOBUF_CONSTEXPR ProtobufInputEvent_MouseEventType(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ProtobufInputEvent_MouseEventType(const ProtobufInputEvent_MouseEventType& from);
  ProtobufInputEvent_MouseEventType(ProtobufInputEvent_MouseEventType&& from) noexcept
    : ProtobufInputEvent_MouseEventType() {
    *this = ::std::move(from);
  }

  inline ProtobufInputEvent_MouseEventType& operator=(const ProtobufInputEvent_MouseEventType& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtobufInputEvent_MouseEventType& operator=(ProtobufInputEvent_MouseEventType&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtobufInputEvent_MouseEventType& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProtobufInputEvent_MouseEventType* internal_default_instance() {
    return reinterpret_cast<const ProtobufInputEvent_MouseEventType*>(
               &_ProtobufInputEvent_MouseEventType_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ProtobufInputEvent_MouseEventType& a, ProtobufInputEvent_MouseEventType& b) {
    a.Swap(&b);
  }
  inline void Swap(ProtobufInputEvent_MouseEventType* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtobufInputEvent_MouseEventType* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtobufInputEvent_MouseEventType* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ProtobufInputEvent_MouseEventType>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ProtobufInputEvent_MouseEventType& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ProtobufInputEvent_MouseEventType& from) {
    ProtobufInputEvent_MouseEventType::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProtobufInputEvent_MouseEventType* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobufGenerated.ProtobufInputEvent.MouseEventType";
  }
  protected:
  explicit ProtobufInputEvent_MouseEventType(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kActionTypeFieldNumber = 3,
    kWheelRotationFieldNumber = 4,
    kRelativePositionFieldNumber = 5,
    kMappedToVirtualDesktopFieldNumber = 6,
  };
  // int32 x = 1;
  void clear_x();
  int32_t x() const;
  void set_x(int32_t value);
  private:
  int32_t _internal_x() const;
  void _internal_set_x(int32_t value);
  public:

  // int32 y = 2;
  void clear_y();
  int32_t y() const;
  void set_y(int32_t value);
  private:
  int32_t _internal_y() const;
  void _internal_set_y(int32_t value);
  public:

  // uint32 actionType = 3;
  void clear_actiontype();
  uint32_t actiontype() const;
  void set_actiontype(uint32_t value);
  private:
  uint32_t _internal_actiontype() const;
  void _internal_set_actiontype(uint32_t value);
  public:

  // uint32 wheelRotation = 4;
  void clear_wheelrotation();
  uint32_t wheelrotation() const;
  void set_wheelrotation(uint32_t value);
  private:
  uint32_t _internal_wheelrotation() const;
  void _internal_set_wheelrotation(uint32_t value);
  public:

  // bool relativePosition = 5;
  void clear_relativeposition();
  bool relativeposition() const;
  void set_relativeposition(bool value);
  private:
  bool _internal_relativeposition() const;
  void _internal_set_relativeposition(bool value);
  public:

  // bool mappedToVirtualDesktop = 6;
  void clear_mappedtovirtualdesktop();
  bool mappedtovirtualdesktop() const;
  void set_mappedtovirtualdesktop(bool value);
  private:
  bool _internal_mappedtovirtualdesktop() const;
  void _internal_set_mappedtovirtualdesktop(bool value);
  public:

  // @@protoc_insertion_point(class_scope:protobufGenerated.ProtobufInputEvent.MouseEventType)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t x_;
    int32_t y_;
    uint32_t actiontype_;
    uint32_t wheelrotation_;
    bool relativeposition_;
    bool mappedtovirtualdesktop_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Events_2eproto;
};
// -------------------------------------------------------------------

class ProtobufInputEvent final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobufGenerated.ProtobufInputEvent) */ {
 public:
  inline ProtobufInputEvent() : ProtobufInputEvent(nullptr) {}
  ~ProtobufInputEvent() override;
  explicit PROTOBUF_CONSTEXPR ProtobufInputEvent(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ProtobufInputEvent(const ProtobufInputEvent& from);
  ProtobufInputEvent(ProtobufInputEvent&& from) noexcept
    : ProtobufInputEvent() {
    *this = ::std::move(from);
  }

  inline ProtobufInputEvent& operator=(const ProtobufInputEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtobufInputEvent& operator=(ProtobufInputEvent&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtobufInputEvent& default_instance() {
    return *internal_default_instance();
  }
  enum EventCase {
    kKeyboardEvent = 2,
    kMouseEvent = 3,
    EVENT_NOT_SET = 0,
  };

  static inline const ProtobufInputEvent* internal_default_instance() {
    return reinterpret_cast<const ProtobufInputEvent*>(
               &_ProtobufInputEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ProtobufInputEvent& a, ProtobufInputEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(ProtobufInputEvent* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtobufInputEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtobufInputEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ProtobufInputEvent>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ProtobufInputEvent& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ProtobufInputEvent& from) {
    ProtobufInputEvent::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProtobufInputEvent* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobufGenerated.ProtobufInputEvent";
  }
  protected:
  explicit ProtobufInputEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ProtobufInputEvent_KeyboardEventType KeyboardEventType;
  typedef ProtobufInputEvent_MouseEventType MouseEventType;

  // accessors -------------------------------------------------------

  enum : int {
    kTimeSinceLastEventFieldNumber = 1,
    kKeyboardEventFieldNumber = 2,
    kMouseEventFieldNumber = 3,
  };
  // uint64 timeSinceLastEvent = 1;
  void clear_timesincelastevent();
  uint64_t timesincelastevent() const;
  void set_timesincelastevent(uint64_t value);
  private:
  uint64_t _internal_timesincelastevent() const;
  void _internal_set_timesincelastevent(uint64_t value);
  public:

  // .protobufGenerated.ProtobufInputEvent.KeyboardEventType keyboardEvent = 2;
  bool has_keyboardevent() const;
  private:
  bool _internal_has_keyboardevent() const;
  public:
  void clear_keyboardevent();
  const ::protobufGenerated::ProtobufInputEvent_KeyboardEventType& keyboardevent() const;
  PROTOBUF_NODISCARD ::protobufGenerated::ProtobufInputEvent_KeyboardEventType* release_keyboardevent();
  ::protobufGenerated::ProtobufInputEvent_KeyboardEventType* mutable_keyboardevent();
  void set_allocated_keyboardevent(::protobufGenerated::ProtobufInputEvent_KeyboardEventType* keyboardevent);
  private:
  const ::protobufGenerated::ProtobufInputEvent_KeyboardEventType& _internal_keyboardevent() const;
  ::protobufGenerated::ProtobufInputEvent_KeyboardEventType* _internal_mutable_keyboardevent();
  public:
  void unsafe_arena_set_allocated_keyboardevent(
      ::protobufGenerated::ProtobufInputEvent_KeyboardEventType* keyboardevent);
  ::protobufGenerated::ProtobufInputEvent_KeyboardEventType* unsafe_arena_release_keyboardevent();

  // .protobufGenerated.ProtobufInputEvent.MouseEventType mouseEvent = 3;
  bool has_mouseevent() const;
  private:
  bool _internal_has_mouseevent() const;
  public:
  void clear_mouseevent();
  const ::protobufGenerated::ProtobufInputEvent_MouseEventType& mouseevent() const;
  PROTOBUF_NODISCARD ::protobufGenerated::ProtobufInputEvent_MouseEventType* release_mouseevent();
  ::protobufGenerated::ProtobufInputEvent_MouseEventType* mutable_mouseevent();
  void set_allocated_mouseevent(::protobufGenerated::ProtobufInputEvent_MouseEventType* mouseevent);
  private:
  const ::protobufGenerated::ProtobufInputEvent_MouseEventType& _internal_mouseevent() const;
  ::protobufGenerated::ProtobufInputEvent_MouseEventType* _internal_mutable_mouseevent();
  public:
  void unsafe_arena_set_allocated_mouseevent(
      ::protobufGenerated::ProtobufInputEvent_MouseEventType* mouseevent);
  ::protobufGenerated::ProtobufInputEvent_MouseEventType* unsafe_arena_release_mouseevent();

  void clear_Event();
  EventCase Event_case() const;
  // @@protoc_insertion_point(class_scope:protobufGenerated.ProtobufInputEvent)
 private:
  class _Internal;
  void set_has_keyboardevent();
  void set_has_mouseevent();

  inline bool has_Event() const;
  inline void clear_has_Event();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t timesincelastevent_;
    union EventUnion {
      constexpr EventUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::protobufGenerated::ProtobufInputEvent_KeyboardEventType* keyboardevent_;
      ::protobufGenerated::ProtobufInputEvent_MouseEventType* mouseevent_;
    } Event_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Events_2eproto;
};
// -------------------------------------------------------------------

class ProtobufInputEventList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobufGenerated.ProtobufInputEventList) */ {
 public:
  inline ProtobufInputEventList() : ProtobufInputEventList(nullptr) {}
  ~ProtobufInputEventList() override;
  explicit PROTOBUF_CONSTEXPR ProtobufInputEventList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ProtobufInputEventList(const ProtobufInputEventList& from);
  ProtobufInputEventList(ProtobufInputEventList&& from) noexcept
    : ProtobufInputEventList() {
    *this = ::std::move(from);
  }

  inline ProtobufInputEventList& operator=(const ProtobufInputEventList& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtobufInputEventList& operator=(ProtobufInputEventList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtobufInputEventList& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProtobufInputEventList* internal_default_instance() {
    return reinterpret_cast<const ProtobufInputEventList*>(
               &_ProtobufInputEventList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ProtobufInputEventList& a, ProtobufInputEventList& b) {
    a.Swap(&b);
  }
  inline void Swap(ProtobufInputEventList* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtobufInputEventList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtobufInputEventList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ProtobufInputEventList>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ProtobufInputEventList& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ProtobufInputEventList& from) {
    ProtobufInputEventList::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProtobufInputEventList* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobufGenerated.ProtobufInputEventList";
  }
  protected:
  explicit ProtobufInputEventList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInputEventsFieldNumber = 1,
  };
  // repeated .protobufGenerated.ProtobufInputEvent inputEvents = 1;
  int inputevents_size() const;
  private:
  int _internal_inputevents_size() const;
  public:
  void clear_inputevents();
  ::protobufGenerated::ProtobufInputEvent* mutable_inputevents(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobufGenerated::ProtobufInputEvent >*
      mutable_inputevents();
  private:
  const ::protobufGenerated::ProtobufInputEvent& _internal_inputevents(int index) const;
  ::protobufGenerated::ProtobufInputEvent* _internal_add_inputevents();
  public:
  const ::protobufGenerated::ProtobufInputEvent& inputevents(int index) const;
  ::protobufGenerated::ProtobufInputEvent* add_inputevents();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobufGenerated::ProtobufInputEvent >&
      inputevents() const;

  // @@protoc_insertion_point(class_scope:protobufGenerated.ProtobufInputEventList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobufGenerated::ProtobufInputEvent > inputevents_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Events_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ProtobufInputEvent_KeyboardEventType

// uint32 virtualKeyCode = 1;
inline void ProtobufInputEvent_KeyboardEventType::clear_virtualkeycode() {
  _impl_.virtualkeycode_ = 0u;
}
inline uint32_t ProtobufInputEvent_KeyboardEventType::_internal_virtualkeycode() const {
  return _impl_.virtualkeycode_;
}
inline uint32_t ProtobufInputEvent_KeyboardEventType::virtualkeycode() const {
  // @@protoc_insertion_point(field_get:protobufGenerated.ProtobufInputEvent.KeyboardEventType.virtualKeyCode)
  return _internal_virtualkeycode();
}
inline void ProtobufInputEvent_KeyboardEventType::_internal_set_virtualkeycode(uint32_t value) {
  
  _impl_.virtualkeycode_ = value;
}
inline void ProtobufInputEvent_KeyboardEventType::set_virtualkeycode(uint32_t value) {
  _internal_set_virtualkeycode(value);
  // @@protoc_insertion_point(field_set:protobufGenerated.ProtobufInputEvent.KeyboardEventType.virtualKeyCode)
}

// bool keyUp = 2;
inline void ProtobufInputEvent_KeyboardEventType::clear_keyup() {
  _impl_.keyup_ = false;
}
inline bool ProtobufInputEvent_KeyboardEventType::_internal_keyup() const {
  return _impl_.keyup_;
}
inline bool ProtobufInputEvent_KeyboardEventType::keyup() const {
  // @@protoc_insertion_point(field_get:protobufGenerated.ProtobufInputEvent.KeyboardEventType.keyUp)
  return _internal_keyup();
}
inline void ProtobufInputEvent_KeyboardEventType::_internal_set_keyup(bool value) {
  
  _impl_.keyup_ = value;
}
inline void ProtobufInputEvent_KeyboardEventType::set_keyup(bool value) {
  _internal_set_keyup(value);
  // @@protoc_insertion_point(field_set:protobufGenerated.ProtobufInputEvent.KeyboardEventType.keyUp)
}

// -------------------------------------------------------------------

// ProtobufInputEvent_MouseEventType

// int32 x = 1;
inline void ProtobufInputEvent_MouseEventType::clear_x() {
  _impl_.x_ = 0;
}
inline int32_t ProtobufInputEvent_MouseEventType::_internal_x() const {
  return _impl_.x_;
}
inline int32_t ProtobufInputEvent_MouseEventType::x() const {
  // @@protoc_insertion_point(field_get:protobufGenerated.ProtobufInputEvent.MouseEventType.x)
  return _internal_x();
}
inline void ProtobufInputEvent_MouseEventType::_internal_set_x(int32_t value) {
  
  _impl_.x_ = value;
}
inline void ProtobufInputEvent_MouseEventType::set_x(int32_t value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:protobufGenerated.ProtobufInputEvent.MouseEventType.x)
}

// int32 y = 2;
inline void ProtobufInputEvent_MouseEventType::clear_y() {
  _impl_.y_ = 0;
}
inline int32_t ProtobufInputEvent_MouseEventType::_internal_y() const {
  return _impl_.y_;
}
inline int32_t ProtobufInputEvent_MouseEventType::y() const {
  // @@protoc_insertion_point(field_get:protobufGenerated.ProtobufInputEvent.MouseEventType.y)
  return _internal_y();
}
inline void ProtobufInputEvent_MouseEventType::_internal_set_y(int32_t value) {
  
  _impl_.y_ = value;
}
inline void ProtobufInputEvent_MouseEventType::set_y(int32_t value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:protobufGenerated.ProtobufInputEvent.MouseEventType.y)
}

// uint32 actionType = 3;
inline void ProtobufInputEvent_MouseEventType::clear_actiontype() {
  _impl_.actiontype_ = 0u;
}
inline uint32_t ProtobufInputEvent_MouseEventType::_internal_actiontype() const {
  return _impl_.actiontype_;
}
inline uint32_t ProtobufInputEvent_MouseEventType::actiontype() const {
  // @@protoc_insertion_point(field_get:protobufGenerated.ProtobufInputEvent.MouseEventType.actionType)
  return _internal_actiontype();
}
inline void ProtobufInputEvent_MouseEventType::_internal_set_actiontype(uint32_t value) {
  
  _impl_.actiontype_ = value;
}
inline void ProtobufInputEvent_MouseEventType::set_actiontype(uint32_t value) {
  _internal_set_actiontype(value);
  // @@protoc_insertion_point(field_set:protobufGenerated.ProtobufInputEvent.MouseEventType.actionType)
}

// uint32 wheelRotation = 4;
inline void ProtobufInputEvent_MouseEventType::clear_wheelrotation() {
  _impl_.wheelrotation_ = 0u;
}
inline uint32_t ProtobufInputEvent_MouseEventType::_internal_wheelrotation() const {
  return _impl_.wheelrotation_;
}
inline uint32_t ProtobufInputEvent_MouseEventType::wheelrotation() const {
  // @@protoc_insertion_point(field_get:protobufGenerated.ProtobufInputEvent.MouseEventType.wheelRotation)
  return _internal_wheelrotation();
}
inline void ProtobufInputEvent_MouseEventType::_internal_set_wheelrotation(uint32_t value) {
  
  _impl_.wheelrotation_ = value;
}
inline void ProtobufInputEvent_MouseEventType::set_wheelrotation(uint32_t value) {
  _internal_set_wheelrotation(value);
  // @@protoc_insertion_point(field_set:protobufGenerated.ProtobufInputEvent.MouseEventType.wheelRotation)
}

// bool relativePosition = 5;
inline void ProtobufInputEvent_MouseEventType::clear_relativeposition() {
  _impl_.relativeposition_ = false;
}
inline bool ProtobufInputEvent_MouseEventType::_internal_relativeposition() const {
  return _impl_.relativeposition_;
}
inline bool ProtobufInputEvent_MouseEventType::relativeposition() const {
  // @@protoc_insertion_point(field_get:protobufGenerated.ProtobufInputEvent.MouseEventType.relativePosition)
  return _internal_relativeposition();
}
inline void ProtobufInputEvent_MouseEventType::_internal_set_relativeposition(bool value) {
  
  _impl_.relativeposition_ = value;
}
inline void ProtobufInputEvent_MouseEventType::set_relativeposition(bool value) {
  _internal_set_relativeposition(value);
  // @@protoc_insertion_point(field_set:protobufGenerated.ProtobufInputEvent.MouseEventType.relativePosition)
}

// bool mappedToVirtualDesktop = 6;
inline void ProtobufInputEvent_MouseEventType::clear_mappedtovirtualdesktop() {
  _impl_.mappedtovirtualdesktop_ = false;
}
inline bool ProtobufInputEvent_MouseEventType::_internal_mappedtovirtualdesktop() const {
  return _impl_.mappedtovirtualdesktop_;
}
inline bool ProtobufInputEvent_MouseEventType::mappedtovirtualdesktop() const {
  // @@protoc_insertion_point(field_get:protobufGenerated.ProtobufInputEvent.MouseEventType.mappedToVirtualDesktop)
  return _internal_mappedtovirtualdesktop();
}
inline void ProtobufInputEvent_MouseEventType::_internal_set_mappedtovirtualdesktop(bool value) {
  
  _impl_.mappedtovirtualdesktop_ = value;
}
inline void ProtobufInputEvent_MouseEventType::set_mappedtovirtualdesktop(bool value) {
  _internal_set_mappedtovirtualdesktop(value);
  // @@protoc_insertion_point(field_set:protobufGenerated.ProtobufInputEvent.MouseEventType.mappedToVirtualDesktop)
}

// -------------------------------------------------------------------

// ProtobufInputEvent

// uint64 timeSinceLastEvent = 1;
inline void ProtobufInputEvent::clear_timesincelastevent() {
  _impl_.timesincelastevent_ = uint64_t{0u};
}
inline uint64_t ProtobufInputEvent::_internal_timesincelastevent() const {
  return _impl_.timesincelastevent_;
}
inline uint64_t ProtobufInputEvent::timesincelastevent() const {
  // @@protoc_insertion_point(field_get:protobufGenerated.ProtobufInputEvent.timeSinceLastEvent)
  return _internal_timesincelastevent();
}
inline void ProtobufInputEvent::_internal_set_timesincelastevent(uint64_t value) {
  
  _impl_.timesincelastevent_ = value;
}
inline void ProtobufInputEvent::set_timesincelastevent(uint64_t value) {
  _internal_set_timesincelastevent(value);
  // @@protoc_insertion_point(field_set:protobufGenerated.ProtobufInputEvent.timeSinceLastEvent)
}

// .protobufGenerated.ProtobufInputEvent.KeyboardEventType keyboardEvent = 2;
inline bool ProtobufInputEvent::_internal_has_keyboardevent() const {
  return Event_case() == kKeyboardEvent;
}
inline bool ProtobufInputEvent::has_keyboardevent() const {
  return _internal_has_keyboardevent();
}
inline void ProtobufInputEvent::set_has_keyboardevent() {
  _impl_._oneof_case_[0] = kKeyboardEvent;
}
inline void ProtobufInputEvent::clear_keyboardevent() {
  if (_internal_has_keyboardevent()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.Event_.keyboardevent_;
    }
    clear_has_Event();
  }
}
inline ::protobufGenerated::ProtobufInputEvent_KeyboardEventType* ProtobufInputEvent::release_keyboardevent() {
  // @@protoc_insertion_point(field_release:protobufGenerated.ProtobufInputEvent.keyboardEvent)
  if (_internal_has_keyboardevent()) {
    clear_has_Event();
    ::protobufGenerated::ProtobufInputEvent_KeyboardEventType* temp = _impl_.Event_.keyboardevent_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.Event_.keyboardevent_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::protobufGenerated::ProtobufInputEvent_KeyboardEventType& ProtobufInputEvent::_internal_keyboardevent() const {
  return _internal_has_keyboardevent()
      ? *_impl_.Event_.keyboardevent_
      : reinterpret_cast< ::protobufGenerated::ProtobufInputEvent_KeyboardEventType&>(::protobufGenerated::_ProtobufInputEvent_KeyboardEventType_default_instance_);
}
inline const ::protobufGenerated::ProtobufInputEvent_KeyboardEventType& ProtobufInputEvent::keyboardevent() const {
  // @@protoc_insertion_point(field_get:protobufGenerated.ProtobufInputEvent.keyboardEvent)
  return _internal_keyboardevent();
}
inline ::protobufGenerated::ProtobufInputEvent_KeyboardEventType* ProtobufInputEvent::unsafe_arena_release_keyboardevent() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protobufGenerated.ProtobufInputEvent.keyboardEvent)
  if (_internal_has_keyboardevent()) {
    clear_has_Event();
    ::protobufGenerated::ProtobufInputEvent_KeyboardEventType* temp = _impl_.Event_.keyboardevent_;
    _impl_.Event_.keyboardevent_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ProtobufInputEvent::unsafe_arena_set_allocated_keyboardevent(::protobufGenerated::ProtobufInputEvent_KeyboardEventType* keyboardevent) {
  clear_Event();
  if (keyboardevent) {
    set_has_keyboardevent();
    _impl_.Event_.keyboardevent_ = keyboardevent;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobufGenerated.ProtobufInputEvent.keyboardEvent)
}
inline ::protobufGenerated::ProtobufInputEvent_KeyboardEventType* ProtobufInputEvent::_internal_mutable_keyboardevent() {
  if (!_internal_has_keyboardevent()) {
    clear_Event();
    set_has_keyboardevent();
    _impl_.Event_.keyboardevent_ = CreateMaybeMessage< ::protobufGenerated::ProtobufInputEvent_KeyboardEventType >(GetArenaForAllocation());
  }
  return _impl_.Event_.keyboardevent_;
}
inline ::protobufGenerated::ProtobufInputEvent_KeyboardEventType* ProtobufInputEvent::mutable_keyboardevent() {
  ::protobufGenerated::ProtobufInputEvent_KeyboardEventType* _msg = _internal_mutable_keyboardevent();
  // @@protoc_insertion_point(field_mutable:protobufGenerated.ProtobufInputEvent.keyboardEvent)
  return _msg;
}

// .protobufGenerated.ProtobufInputEvent.MouseEventType mouseEvent = 3;
inline bool ProtobufInputEvent::_internal_has_mouseevent() const {
  return Event_case() == kMouseEvent;
}
inline bool ProtobufInputEvent::has_mouseevent() const {
  return _internal_has_mouseevent();
}
inline void ProtobufInputEvent::set_has_mouseevent() {
  _impl_._oneof_case_[0] = kMouseEvent;
}
inline void ProtobufInputEvent::clear_mouseevent() {
  if (_internal_has_mouseevent()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.Event_.mouseevent_;
    }
    clear_has_Event();
  }
}
inline ::protobufGenerated::ProtobufInputEvent_MouseEventType* ProtobufInputEvent::release_mouseevent() {
  // @@protoc_insertion_point(field_release:protobufGenerated.ProtobufInputEvent.mouseEvent)
  if (_internal_has_mouseevent()) {
    clear_has_Event();
    ::protobufGenerated::ProtobufInputEvent_MouseEventType* temp = _impl_.Event_.mouseevent_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.Event_.mouseevent_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::protobufGenerated::ProtobufInputEvent_MouseEventType& ProtobufInputEvent::_internal_mouseevent() const {
  return _internal_has_mouseevent()
      ? *_impl_.Event_.mouseevent_
      : reinterpret_cast< ::protobufGenerated::ProtobufInputEvent_MouseEventType&>(::protobufGenerated::_ProtobufInputEvent_MouseEventType_default_instance_);
}
inline const ::protobufGenerated::ProtobufInputEvent_MouseEventType& ProtobufInputEvent::mouseevent() const {
  // @@protoc_insertion_point(field_get:protobufGenerated.ProtobufInputEvent.mouseEvent)
  return _internal_mouseevent();
}
inline ::protobufGenerated::ProtobufInputEvent_MouseEventType* ProtobufInputEvent::unsafe_arena_release_mouseevent() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protobufGenerated.ProtobufInputEvent.mouseEvent)
  if (_internal_has_mouseevent()) {
    clear_has_Event();
    ::protobufGenerated::ProtobufInputEvent_MouseEventType* temp = _impl_.Event_.mouseevent_;
    _impl_.Event_.mouseevent_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ProtobufInputEvent::unsafe_arena_set_allocated_mouseevent(::protobufGenerated::ProtobufInputEvent_MouseEventType* mouseevent) {
  clear_Event();
  if (mouseevent) {
    set_has_mouseevent();
    _impl_.Event_.mouseevent_ = mouseevent;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobufGenerated.ProtobufInputEvent.mouseEvent)
}
inline ::protobufGenerated::ProtobufInputEvent_MouseEventType* ProtobufInputEvent::_internal_mutable_mouseevent() {
  if (!_internal_has_mouseevent()) {
    clear_Event();
    set_has_mouseevent();
    _impl_.Event_.mouseevent_ = CreateMaybeMessage< ::protobufGenerated::ProtobufInputEvent_MouseEventType >(GetArenaForAllocation());
  }
  return _impl_.Event_.mouseevent_;
}
inline ::protobufGenerated::ProtobufInputEvent_MouseEventType* ProtobufInputEvent::mutable_mouseevent() {
  ::protobufGenerated::ProtobufInputEvent_MouseEventType* _msg = _internal_mutable_mouseevent();
  // @@protoc_insertion_point(field_mutable:protobufGenerated.ProtobufInputEvent.mouseEvent)
  return _msg;
}

inline bool ProtobufInputEvent::has_Event() const {
  return Event_case() != EVENT_NOT_SET;
}
inline void ProtobufInputEvent::clear_has_Event() {
  _impl_._oneof_case_[0] = EVENT_NOT_SET;
}
inline ProtobufInputEvent::EventCase ProtobufInputEvent::Event_case() const {
  return ProtobufInputEvent::EventCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// ProtobufInputEventList

// repeated .protobufGenerated.ProtobufInputEvent inputEvents = 1;
inline int ProtobufInputEventList::_internal_inputevents_size() const {
  return _impl_.inputevents_.size();
}
inline int ProtobufInputEventList::inputevents_size() const {
  return _internal_inputevents_size();
}
inline void ProtobufInputEventList::clear_inputevents() {
  _impl_.inputevents_.Clear();
}
inline ::protobufGenerated::ProtobufInputEvent* ProtobufInputEventList::mutable_inputevents(int index) {
  // @@protoc_insertion_point(field_mutable:protobufGenerated.ProtobufInputEventList.inputEvents)
  return _impl_.inputevents_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobufGenerated::ProtobufInputEvent >*
ProtobufInputEventList::mutable_inputevents() {
  // @@protoc_insertion_point(field_mutable_list:protobufGenerated.ProtobufInputEventList.inputEvents)
  return &_impl_.inputevents_;
}
inline const ::protobufGenerated::ProtobufInputEvent& ProtobufInputEventList::_internal_inputevents(int index) const {
  return _impl_.inputevents_.Get(index);
}
inline const ::protobufGenerated::ProtobufInputEvent& ProtobufInputEventList::inputevents(int index) const {
  // @@protoc_insertion_point(field_get:protobufGenerated.ProtobufInputEventList.inputEvents)
  return _internal_inputevents(index);
}
inline ::protobufGenerated::ProtobufInputEvent* ProtobufInputEventList::_internal_add_inputevents() {
  return _impl_.inputevents_.Add();
}
inline ::protobufGenerated::ProtobufInputEvent* ProtobufInputEventList::add_inputevents() {
  ::protobufGenerated::ProtobufInputEvent* _add = _internal_add_inputevents();
  // @@protoc_insertion_point(field_add:protobufGenerated.ProtobufInputEventList.inputEvents)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobufGenerated::ProtobufInputEvent >&
ProtobufInputEventList::inputevents() const {
  // @@protoc_insertion_point(field_list:protobufGenerated.ProtobufInputEventList.inputEvents)
  return _impl_.inputevents_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobufGenerated

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Events_2eproto
