// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Events.proto

#include "Events.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace protobufGenerated {
PROTOBUF_CONSTEXPR ProtobufInputEvent_KeyboardEventType::ProtobufInputEvent_KeyboardEventType(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.virtualkeycode_)*/0u
  , /*decltype(_impl_.keyup_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ProtobufInputEvent_KeyboardEventTypeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufInputEvent_KeyboardEventTypeDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufInputEvent_KeyboardEventTypeDefaultTypeInternal() {}
  union {
    ProtobufInputEvent_KeyboardEventType _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufInputEvent_KeyboardEventTypeDefaultTypeInternal _ProtobufInputEvent_KeyboardEventType_default_instance_;
PROTOBUF_CONSTEXPR ProtobufInputEvent_MouseEventType::ProtobufInputEvent_MouseEventType(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.x_)*/0
  , /*decltype(_impl_.y_)*/0
  , /*decltype(_impl_.actiontype_)*/0u
  , /*decltype(_impl_.wheelrotation_)*/0u
  , /*decltype(_impl_.relativeposition_)*/false
  , /*decltype(_impl_.mappedtovirtualdesktop_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ProtobufInputEvent_MouseEventTypeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufInputEvent_MouseEventTypeDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufInputEvent_MouseEventTypeDefaultTypeInternal() {}
  union {
    ProtobufInputEvent_MouseEventType _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufInputEvent_MouseEventTypeDefaultTypeInternal _ProtobufInputEvent_MouseEventType_default_instance_;
PROTOBUF_CONSTEXPR ProtobufInputEvent::ProtobufInputEvent(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.timesincestartofrecording_)*/uint64_t{0u}
  , /*decltype(_impl_.Event_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct ProtobufInputEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufInputEventDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufInputEventDefaultTypeInternal() {}
  union {
    ProtobufInputEvent _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufInputEventDefaultTypeInternal _ProtobufInputEvent_default_instance_;
PROTOBUF_CONSTEXPR ProtobufInputEventList::ProtobufInputEventList(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.inputevents_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ProtobufInputEventListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufInputEventListDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufInputEventListDefaultTypeInternal() {}
  union {
    ProtobufInputEventList _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufInputEventListDefaultTypeInternal _ProtobufInputEventList_default_instance_;
}  // namespace protobufGenerated
static ::_pb::Metadata file_level_metadata_Events_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Events_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Events_2eproto = nullptr;

const uint32_t TableStruct_Events_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobufGenerated::ProtobufInputEvent_KeyboardEventType, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protobufGenerated::ProtobufInputEvent_KeyboardEventType, _impl_.virtualkeycode_),
  PROTOBUF_FIELD_OFFSET(::protobufGenerated::ProtobufInputEvent_KeyboardEventType, _impl_.keyup_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobufGenerated::ProtobufInputEvent_MouseEventType, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protobufGenerated::ProtobufInputEvent_MouseEventType, _impl_.x_),
  PROTOBUF_FIELD_OFFSET(::protobufGenerated::ProtobufInputEvent_MouseEventType, _impl_.y_),
  PROTOBUF_FIELD_OFFSET(::protobufGenerated::ProtobufInputEvent_MouseEventType, _impl_.actiontype_),
  PROTOBUF_FIELD_OFFSET(::protobufGenerated::ProtobufInputEvent_MouseEventType, _impl_.wheelrotation_),
  PROTOBUF_FIELD_OFFSET(::protobufGenerated::ProtobufInputEvent_MouseEventType, _impl_.relativeposition_),
  PROTOBUF_FIELD_OFFSET(::protobufGenerated::ProtobufInputEvent_MouseEventType, _impl_.mappedtovirtualdesktop_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobufGenerated::ProtobufInputEvent, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::protobufGenerated::ProtobufInputEvent, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protobufGenerated::ProtobufInputEvent, _impl_.timesincestartofrecording_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::protobufGenerated::ProtobufInputEvent, _impl_.Event_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobufGenerated::ProtobufInputEventList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protobufGenerated::ProtobufInputEventList, _impl_.inputevents_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::protobufGenerated::ProtobufInputEvent_KeyboardEventType)},
  { 8, -1, -1, sizeof(::protobufGenerated::ProtobufInputEvent_MouseEventType)},
  { 20, -1, -1, sizeof(::protobufGenerated::ProtobufInputEvent)},
  { 30, -1, -1, sizeof(::protobufGenerated::ProtobufInputEventList)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::protobufGenerated::_ProtobufInputEvent_KeyboardEventType_default_instance_._instance,
  &::protobufGenerated::_ProtobufInputEvent_MouseEventType_default_instance_._instance,
  &::protobufGenerated::_ProtobufInputEvent_default_instance_._instance,
  &::protobufGenerated::_ProtobufInputEventList_default_instance_._instance,
};

const char descriptor_table_protodef_Events_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014Events.proto\022\021protobufGenerated\"\250\003\n\022Pr"
  "otobufInputEvent\022!\n\031timeSinceStartOfReco"
  "rding\030\001 \001(\004\022P\n\rkeyboardEvent\030\002 \001(\01327.pro"
  "tobufGenerated.ProtobufInputEvent.Keyboa"
  "rdEventTypeH\000\022J\n\nmouseEvent\030\003 \001(\01324.prot"
  "obufGenerated.ProtobufInputEvent.MouseEv"
  "entTypeH\000\032:\n\021KeyboardEventType\022\026\n\016virtua"
  "lKeyCode\030\001 \001(\r\022\r\n\005keyUp\030\002 \001(\010\032\213\001\n\016MouseE"
  "ventType\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\005\022\022\n\naction"
  "Type\030\003 \001(\r\022\025\n\rwheelRotation\030\004 \001(\r\022\030\n\020rel"
  "ativePosition\030\005 \001(\010\022\036\n\026mappedToVirtualDe"
  "sktop\030\006 \001(\010B\007\n\005Event\"T\n\026ProtobufInputEve"
  "ntList\022:\n\013inputEvents\030\001 \003(\0132%.protobufGe"
  "nerated.ProtobufInputEventb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_Events_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Events_2eproto = {
    false, false, 554, descriptor_table_protodef_Events_2eproto,
    "Events.proto",
    &descriptor_table_Events_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_Events_2eproto::offsets,
    file_level_metadata_Events_2eproto, file_level_enum_descriptors_Events_2eproto,
    file_level_service_descriptors_Events_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Events_2eproto_getter() {
  return &descriptor_table_Events_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Events_2eproto(&descriptor_table_Events_2eproto);
namespace protobufGenerated {

// ===================================================================

class ProtobufInputEvent_KeyboardEventType::_Internal {
 public:
};

ProtobufInputEvent_KeyboardEventType::ProtobufInputEvent_KeyboardEventType(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobufGenerated.ProtobufInputEvent.KeyboardEventType)
}
ProtobufInputEvent_KeyboardEventType::ProtobufInputEvent_KeyboardEventType(const ProtobufInputEvent_KeyboardEventType& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ProtobufInputEvent_KeyboardEventType* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.virtualkeycode_){}
    , decltype(_impl_.keyup_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.virtualkeycode_, &from._impl_.virtualkeycode_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.keyup_) -
    reinterpret_cast<char*>(&_impl_.virtualkeycode_)) + sizeof(_impl_.keyup_));
  // @@protoc_insertion_point(copy_constructor:protobufGenerated.ProtobufInputEvent.KeyboardEventType)
}

inline void ProtobufInputEvent_KeyboardEventType::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.virtualkeycode_){0u}
    , decltype(_impl_.keyup_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ProtobufInputEvent_KeyboardEventType::~ProtobufInputEvent_KeyboardEventType() {
  // @@protoc_insertion_point(destructor:protobufGenerated.ProtobufInputEvent.KeyboardEventType)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ProtobufInputEvent_KeyboardEventType::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ProtobufInputEvent_KeyboardEventType::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ProtobufInputEvent_KeyboardEventType::Clear() {
// @@protoc_insertion_point(message_clear_start:protobufGenerated.ProtobufInputEvent.KeyboardEventType)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.virtualkeycode_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.keyup_) -
      reinterpret_cast<char*>(&_impl_.virtualkeycode_)) + sizeof(_impl_.keyup_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProtobufInputEvent_KeyboardEventType::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 virtualKeyCode = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.virtualkeycode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool keyUp = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.keyup_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ProtobufInputEvent_KeyboardEventType::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobufGenerated.ProtobufInputEvent.KeyboardEventType)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 virtualKeyCode = 1;
  if (this->_internal_virtualkeycode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_virtualkeycode(), target);
  }

  // bool keyUp = 2;
  if (this->_internal_keyup() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_keyup(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobufGenerated.ProtobufInputEvent.KeyboardEventType)
  return target;
}

size_t ProtobufInputEvent_KeyboardEventType::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobufGenerated.ProtobufInputEvent.KeyboardEventType)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 virtualKeyCode = 1;
  if (this->_internal_virtualkeycode() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_virtualkeycode());
  }

  // bool keyUp = 2;
  if (this->_internal_keyup() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ProtobufInputEvent_KeyboardEventType::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ProtobufInputEvent_KeyboardEventType::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ProtobufInputEvent_KeyboardEventType::GetClassData() const { return &_class_data_; }


void ProtobufInputEvent_KeyboardEventType::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ProtobufInputEvent_KeyboardEventType*>(&to_msg);
  auto& from = static_cast<const ProtobufInputEvent_KeyboardEventType&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobufGenerated.ProtobufInputEvent.KeyboardEventType)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_virtualkeycode() != 0) {
    _this->_internal_set_virtualkeycode(from._internal_virtualkeycode());
  }
  if (from._internal_keyup() != 0) {
    _this->_internal_set_keyup(from._internal_keyup());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufInputEvent_KeyboardEventType::CopyFrom(const ProtobufInputEvent_KeyboardEventType& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobufGenerated.ProtobufInputEvent.KeyboardEventType)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtobufInputEvent_KeyboardEventType::IsInitialized() const {
  return true;
}

void ProtobufInputEvent_KeyboardEventType::InternalSwap(ProtobufInputEvent_KeyboardEventType* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufInputEvent_KeyboardEventType, _impl_.keyup_)
      + sizeof(ProtobufInputEvent_KeyboardEventType::_impl_.keyup_)
      - PROTOBUF_FIELD_OFFSET(ProtobufInputEvent_KeyboardEventType, _impl_.virtualkeycode_)>(
          reinterpret_cast<char*>(&_impl_.virtualkeycode_),
          reinterpret_cast<char*>(&other->_impl_.virtualkeycode_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ProtobufInputEvent_KeyboardEventType::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Events_2eproto_getter, &descriptor_table_Events_2eproto_once,
      file_level_metadata_Events_2eproto[0]);
}

// ===================================================================

class ProtobufInputEvent_MouseEventType::_Internal {
 public:
};

ProtobufInputEvent_MouseEventType::ProtobufInputEvent_MouseEventType(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobufGenerated.ProtobufInputEvent.MouseEventType)
}
ProtobufInputEvent_MouseEventType::ProtobufInputEvent_MouseEventType(const ProtobufInputEvent_MouseEventType& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ProtobufInputEvent_MouseEventType* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){}
    , decltype(_impl_.y_){}
    , decltype(_impl_.actiontype_){}
    , decltype(_impl_.wheelrotation_){}
    , decltype(_impl_.relativeposition_){}
    , decltype(_impl_.mappedtovirtualdesktop_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.x_, &from._impl_.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.mappedtovirtualdesktop_) -
    reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.mappedtovirtualdesktop_));
  // @@protoc_insertion_point(copy_constructor:protobufGenerated.ProtobufInputEvent.MouseEventType)
}

inline void ProtobufInputEvent_MouseEventType::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){0}
    , decltype(_impl_.y_){0}
    , decltype(_impl_.actiontype_){0u}
    , decltype(_impl_.wheelrotation_){0u}
    , decltype(_impl_.relativeposition_){false}
    , decltype(_impl_.mappedtovirtualdesktop_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ProtobufInputEvent_MouseEventType::~ProtobufInputEvent_MouseEventType() {
  // @@protoc_insertion_point(destructor:protobufGenerated.ProtobufInputEvent.MouseEventType)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ProtobufInputEvent_MouseEventType::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ProtobufInputEvent_MouseEventType::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ProtobufInputEvent_MouseEventType::Clear() {
// @@protoc_insertion_point(message_clear_start:protobufGenerated.ProtobufInputEvent.MouseEventType)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.mappedtovirtualdesktop_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.mappedtovirtualdesktop_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProtobufInputEvent_MouseEventType::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.x_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.y_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 actionType = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.actiontype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 wheelRotation = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.wheelrotation_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool relativePosition = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.relativeposition_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool mappedToVirtualDesktop = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.mappedtovirtualdesktop_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ProtobufInputEvent_MouseEventType::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobufGenerated.ProtobufInputEvent.MouseEventType)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 x = 1;
  if (this->_internal_x() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_x(), target);
  }

  // int32 y = 2;
  if (this->_internal_y() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_y(), target);
  }

  // uint32 actionType = 3;
  if (this->_internal_actiontype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_actiontype(), target);
  }

  // uint32 wheelRotation = 4;
  if (this->_internal_wheelrotation() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_wheelrotation(), target);
  }

  // bool relativePosition = 5;
  if (this->_internal_relativeposition() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(5, this->_internal_relativeposition(), target);
  }

  // bool mappedToVirtualDesktop = 6;
  if (this->_internal_mappedtovirtualdesktop() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(6, this->_internal_mappedtovirtualdesktop(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobufGenerated.ProtobufInputEvent.MouseEventType)
  return target;
}

size_t ProtobufInputEvent_MouseEventType::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobufGenerated.ProtobufInputEvent.MouseEventType)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 x = 1;
  if (this->_internal_x() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_x());
  }

  // int32 y = 2;
  if (this->_internal_y() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_y());
  }

  // uint32 actionType = 3;
  if (this->_internal_actiontype() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_actiontype());
  }

  // uint32 wheelRotation = 4;
  if (this->_internal_wheelrotation() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_wheelrotation());
  }

  // bool relativePosition = 5;
  if (this->_internal_relativeposition() != 0) {
    total_size += 1 + 1;
  }

  // bool mappedToVirtualDesktop = 6;
  if (this->_internal_mappedtovirtualdesktop() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ProtobufInputEvent_MouseEventType::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ProtobufInputEvent_MouseEventType::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ProtobufInputEvent_MouseEventType::GetClassData() const { return &_class_data_; }


void ProtobufInputEvent_MouseEventType::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ProtobufInputEvent_MouseEventType*>(&to_msg);
  auto& from = static_cast<const ProtobufInputEvent_MouseEventType&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobufGenerated.ProtobufInputEvent.MouseEventType)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_x() != 0) {
    _this->_internal_set_x(from._internal_x());
  }
  if (from._internal_y() != 0) {
    _this->_internal_set_y(from._internal_y());
  }
  if (from._internal_actiontype() != 0) {
    _this->_internal_set_actiontype(from._internal_actiontype());
  }
  if (from._internal_wheelrotation() != 0) {
    _this->_internal_set_wheelrotation(from._internal_wheelrotation());
  }
  if (from._internal_relativeposition() != 0) {
    _this->_internal_set_relativeposition(from._internal_relativeposition());
  }
  if (from._internal_mappedtovirtualdesktop() != 0) {
    _this->_internal_set_mappedtovirtualdesktop(from._internal_mappedtovirtualdesktop());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufInputEvent_MouseEventType::CopyFrom(const ProtobufInputEvent_MouseEventType& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobufGenerated.ProtobufInputEvent.MouseEventType)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtobufInputEvent_MouseEventType::IsInitialized() const {
  return true;
}

void ProtobufInputEvent_MouseEventType::InternalSwap(ProtobufInputEvent_MouseEventType* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufInputEvent_MouseEventType, _impl_.mappedtovirtualdesktop_)
      + sizeof(ProtobufInputEvent_MouseEventType::_impl_.mappedtovirtualdesktop_)
      - PROTOBUF_FIELD_OFFSET(ProtobufInputEvent_MouseEventType, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ProtobufInputEvent_MouseEventType::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Events_2eproto_getter, &descriptor_table_Events_2eproto_once,
      file_level_metadata_Events_2eproto[1]);
}

// ===================================================================

class ProtobufInputEvent::_Internal {
 public:
  static const ::protobufGenerated::ProtobufInputEvent_KeyboardEventType& keyboardevent(const ProtobufInputEvent* msg);
  static const ::protobufGenerated::ProtobufInputEvent_MouseEventType& mouseevent(const ProtobufInputEvent* msg);
};

const ::protobufGenerated::ProtobufInputEvent_KeyboardEventType&
ProtobufInputEvent::_Internal::keyboardevent(const ProtobufInputEvent* msg) {
  return *msg->_impl_.Event_.keyboardevent_;
}
const ::protobufGenerated::ProtobufInputEvent_MouseEventType&
ProtobufInputEvent::_Internal::mouseevent(const ProtobufInputEvent* msg) {
  return *msg->_impl_.Event_.mouseevent_;
}
void ProtobufInputEvent::set_allocated_keyboardevent(::protobufGenerated::ProtobufInputEvent_KeyboardEventType* keyboardevent) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_Event();
  if (keyboardevent) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(keyboardevent);
    if (message_arena != submessage_arena) {
      keyboardevent = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, keyboardevent, submessage_arena);
    }
    set_has_keyboardevent();
    _impl_.Event_.keyboardevent_ = keyboardevent;
  }
  // @@protoc_insertion_point(field_set_allocated:protobufGenerated.ProtobufInputEvent.keyboardEvent)
}
void ProtobufInputEvent::set_allocated_mouseevent(::protobufGenerated::ProtobufInputEvent_MouseEventType* mouseevent) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_Event();
  if (mouseevent) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(mouseevent);
    if (message_arena != submessage_arena) {
      mouseevent = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, mouseevent, submessage_arena);
    }
    set_has_mouseevent();
    _impl_.Event_.mouseevent_ = mouseevent;
  }
  // @@protoc_insertion_point(field_set_allocated:protobufGenerated.ProtobufInputEvent.mouseEvent)
}
ProtobufInputEvent::ProtobufInputEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobufGenerated.ProtobufInputEvent)
}
ProtobufInputEvent::ProtobufInputEvent(const ProtobufInputEvent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ProtobufInputEvent* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.timesincestartofrecording_){}
    , decltype(_impl_.Event_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.timesincestartofrecording_ = from._impl_.timesincestartofrecording_;
  clear_has_Event();
  switch (from.Event_case()) {
    case kKeyboardEvent: {
      _this->_internal_mutable_keyboardevent()->::protobufGenerated::ProtobufInputEvent_KeyboardEventType::MergeFrom(
          from._internal_keyboardevent());
      break;
    }
    case kMouseEvent: {
      _this->_internal_mutable_mouseevent()->::protobufGenerated::ProtobufInputEvent_MouseEventType::MergeFrom(
          from._internal_mouseevent());
      break;
    }
    case EVENT_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:protobufGenerated.ProtobufInputEvent)
}

inline void ProtobufInputEvent::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.timesincestartofrecording_){uint64_t{0u}}
    , decltype(_impl_.Event_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_Event();
}

ProtobufInputEvent::~ProtobufInputEvent() {
  // @@protoc_insertion_point(destructor:protobufGenerated.ProtobufInputEvent)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ProtobufInputEvent::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_Event()) {
    clear_Event();
  }
}

void ProtobufInputEvent::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ProtobufInputEvent::clear_Event() {
// @@protoc_insertion_point(one_of_clear_start:protobufGenerated.ProtobufInputEvent)
  switch (Event_case()) {
    case kKeyboardEvent: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.Event_.keyboardevent_;
      }
      break;
    }
    case kMouseEvent: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.Event_.mouseevent_;
      }
      break;
    }
    case EVENT_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = EVENT_NOT_SET;
}


void ProtobufInputEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:protobufGenerated.ProtobufInputEvent)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.timesincestartofrecording_ = uint64_t{0u};
  clear_Event();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProtobufInputEvent::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 timeSinceStartOfRecording = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.timesincestartofrecording_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .protobufGenerated.ProtobufInputEvent.KeyboardEventType keyboardEvent = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_keyboardevent(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .protobufGenerated.ProtobufInputEvent.MouseEventType mouseEvent = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_mouseevent(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ProtobufInputEvent::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobufGenerated.ProtobufInputEvent)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 timeSinceStartOfRecording = 1;
  if (this->_internal_timesincestartofrecording() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_timesincestartofrecording(), target);
  }

  // .protobufGenerated.ProtobufInputEvent.KeyboardEventType keyboardEvent = 2;
  if (_internal_has_keyboardevent()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::keyboardevent(this),
        _Internal::keyboardevent(this).GetCachedSize(), target, stream);
  }

  // .protobufGenerated.ProtobufInputEvent.MouseEventType mouseEvent = 3;
  if (_internal_has_mouseevent()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::mouseevent(this),
        _Internal::mouseevent(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobufGenerated.ProtobufInputEvent)
  return target;
}

size_t ProtobufInputEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobufGenerated.ProtobufInputEvent)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 timeSinceStartOfRecording = 1;
  if (this->_internal_timesincestartofrecording() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_timesincestartofrecording());
  }

  switch (Event_case()) {
    // .protobufGenerated.ProtobufInputEvent.KeyboardEventType keyboardEvent = 2;
    case kKeyboardEvent: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.Event_.keyboardevent_);
      break;
    }
    // .protobufGenerated.ProtobufInputEvent.MouseEventType mouseEvent = 3;
    case kMouseEvent: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.Event_.mouseevent_);
      break;
    }
    case EVENT_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ProtobufInputEvent::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ProtobufInputEvent::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ProtobufInputEvent::GetClassData() const { return &_class_data_; }


void ProtobufInputEvent::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ProtobufInputEvent*>(&to_msg);
  auto& from = static_cast<const ProtobufInputEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobufGenerated.ProtobufInputEvent)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_timesincestartofrecording() != 0) {
    _this->_internal_set_timesincestartofrecording(from._internal_timesincestartofrecording());
  }
  switch (from.Event_case()) {
    case kKeyboardEvent: {
      _this->_internal_mutable_keyboardevent()->::protobufGenerated::ProtobufInputEvent_KeyboardEventType::MergeFrom(
          from._internal_keyboardevent());
      break;
    }
    case kMouseEvent: {
      _this->_internal_mutable_mouseevent()->::protobufGenerated::ProtobufInputEvent_MouseEventType::MergeFrom(
          from._internal_mouseevent());
      break;
    }
    case EVENT_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufInputEvent::CopyFrom(const ProtobufInputEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobufGenerated.ProtobufInputEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtobufInputEvent::IsInitialized() const {
  return true;
}

void ProtobufInputEvent::InternalSwap(ProtobufInputEvent* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.timesincestartofrecording_, other->_impl_.timesincestartofrecording_);
  swap(_impl_.Event_, other->_impl_.Event_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata ProtobufInputEvent::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Events_2eproto_getter, &descriptor_table_Events_2eproto_once,
      file_level_metadata_Events_2eproto[2]);
}

// ===================================================================

class ProtobufInputEventList::_Internal {
 public:
};

ProtobufInputEventList::ProtobufInputEventList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobufGenerated.ProtobufInputEventList)
}
ProtobufInputEventList::ProtobufInputEventList(const ProtobufInputEventList& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ProtobufInputEventList* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.inputevents_){from._impl_.inputevents_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:protobufGenerated.ProtobufInputEventList)
}

inline void ProtobufInputEventList::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.inputevents_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ProtobufInputEventList::~ProtobufInputEventList() {
  // @@protoc_insertion_point(destructor:protobufGenerated.ProtobufInputEventList)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ProtobufInputEventList::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.inputevents_.~RepeatedPtrField();
}

void ProtobufInputEventList::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ProtobufInputEventList::Clear() {
// @@protoc_insertion_point(message_clear_start:protobufGenerated.ProtobufInputEventList)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.inputevents_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProtobufInputEventList::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .protobufGenerated.ProtobufInputEvent inputEvents = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_inputevents(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ProtobufInputEventList::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobufGenerated.ProtobufInputEventList)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .protobufGenerated.ProtobufInputEvent inputEvents = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_inputevents_size()); i < n; i++) {
    const auto& repfield = this->_internal_inputevents(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobufGenerated.ProtobufInputEventList)
  return target;
}

size_t ProtobufInputEventList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobufGenerated.ProtobufInputEventList)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .protobufGenerated.ProtobufInputEvent inputEvents = 1;
  total_size += 1UL * this->_internal_inputevents_size();
  for (const auto& msg : this->_impl_.inputevents_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ProtobufInputEventList::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ProtobufInputEventList::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ProtobufInputEventList::GetClassData() const { return &_class_data_; }


void ProtobufInputEventList::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ProtobufInputEventList*>(&to_msg);
  auto& from = static_cast<const ProtobufInputEventList&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobufGenerated.ProtobufInputEventList)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.inputevents_.MergeFrom(from._impl_.inputevents_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufInputEventList::CopyFrom(const ProtobufInputEventList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobufGenerated.ProtobufInputEventList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtobufInputEventList::IsInitialized() const {
  return true;
}

void ProtobufInputEventList::InternalSwap(ProtobufInputEventList* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.inputevents_.InternalSwap(&other->_impl_.inputevents_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ProtobufInputEventList::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Events_2eproto_getter, &descriptor_table_Events_2eproto_once,
      file_level_metadata_Events_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobufGenerated
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobufGenerated::ProtobufInputEvent_KeyboardEventType*
Arena::CreateMaybeMessage< ::protobufGenerated::ProtobufInputEvent_KeyboardEventType >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobufGenerated::ProtobufInputEvent_KeyboardEventType >(arena);
}
template<> PROTOBUF_NOINLINE ::protobufGenerated::ProtobufInputEvent_MouseEventType*
Arena::CreateMaybeMessage< ::protobufGenerated::ProtobufInputEvent_MouseEventType >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobufGenerated::ProtobufInputEvent_MouseEventType >(arena);
}
template<> PROTOBUF_NOINLINE ::protobufGenerated::ProtobufInputEvent*
Arena::CreateMaybeMessage< ::protobufGenerated::ProtobufInputEvent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobufGenerated::ProtobufInputEvent >(arena);
}
template<> PROTOBUF_NOINLINE ::protobufGenerated::ProtobufInputEventList*
Arena::CreateMaybeMessage< ::protobufGenerated::ProtobufInputEventList >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobufGenerated::ProtobufInputEventList >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
